spring.application.name=taskflow-api

spring.config.import=file:./.env[.properties]

# Spring AI - OpenAI Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.temperature=0.7
